import { PrismaClient, TechnologyCategory } from '../../generated/prisma/client';

export async function seedTechnologies(prisma: PrismaClient) {
  console.log('Seeding technologies...');

  const technologiesData: Array<{ name: string; category: TechnologyCategory }> = [
    // FRONTEND
    { name: 'JavaScript', category: TechnologyCategory.FRONTEND },
    { name: 'TypeScript', category: TechnologyCategory.FRONTEND },
    { name: 'React', category: TechnologyCategory.FRONTEND },
    { name: 'Vue.js', category: TechnologyCategory.FRONTEND },
    { name: 'Angular', category: TechnologyCategory.FRONTEND },
    { name: 'Next.js', category: TechnologyCategory.FRONTEND },
    { name: 'Nuxt.js', category: TechnologyCategory.FRONTEND },
    { name: 'Svelte', category: TechnologyCategory.FRONTEND },
    { name: 'SvelteKit', category: TechnologyCategory.FRONTEND },
    { name: 'HTML5', category: TechnologyCategory.FRONTEND },
    { name: 'CSS3', category: TechnologyCategory.FRONTEND },
    { name: 'Sass / SCSS', category: TechnologyCategory.FRONTEND },
    { name: 'Tailwind CSS', category: TechnologyCategory.FRONTEND },
    { name: 'Bootstrap', category: TechnologyCategory.FRONTEND },
    { name: 'MUI (Material UI)', category: TechnologyCategory.FRONTEND },
    { name: 'Chakra UI', category: TechnologyCategory.FRONTEND },
    { name: 'Shadcn UI', category: TechnologyCategory.FRONTEND },
    { name: 'Redux', category: TechnologyCategory.FRONTEND },
    { name: 'Zustand', category: TechnologyCategory.FRONTEND },
    { name: 'TanStack Query (React Query)', category: TechnologyCategory.FRONTEND },
    { name: 'Astro', category: TechnologyCategory.FRONTEND },
    { name: 'Alpine.js', category: TechnologyCategory.FRONTEND },
    { name: 'RxJS', category: TechnologyCategory.FRONTEND },
    { name: 'Webpack', category: TechnologyCategory.FRONTEND },
    { name: 'Vite', category: TechnologyCategory.FRONTEND },

    // BACKEND
    { name: 'Node.js', category: TechnologyCategory.BACKEND },
    { name: 'NestJS', category: TechnologyCategory.BACKEND },
    { name: 'Express.js', category: TechnologyCategory.BACKEND },
    { name: 'Python', category: TechnologyCategory.BACKEND },
    { name: 'Django', category: TechnologyCategory.BACKEND },
    { name: 'FastAPI', category: TechnologyCategory.BACKEND },
    { name: 'Flask', category: TechnologyCategory.BACKEND },
    { name: 'Java', category: TechnologyCategory.BACKEND },
    { name: 'Spring Boot', category: TechnologyCategory.BACKEND },
    { name: 'C#', category: TechnologyCategory.BACKEND },
    { name: '.NET', category: TechnologyCategory.BACKEND },
    { name: 'ASP.NET Core', category: TechnologyCategory.BACKEND },
    { name: 'PHP', category: TechnologyCategory.BACKEND },
    { name: 'Laravel', category: TechnologyCategory.BACKEND },
    { name: 'Symfony', category: TechnologyCategory.BACKEND },
    { name: 'Ruby', category: TechnologyCategory.BACKEND },
    { name: 'Ruby on Rails', category: TechnologyCategory.BACKEND },
    { name: 'Go (Golang)', category: TechnologyCategory.BACKEND },
    { name: 'Rust', category: TechnologyCategory.BACKEND },
    { name: 'Kotlin', category: TechnologyCategory.BACKEND },
    { name: 'Scala', category: TechnologyCategory.BACKEND },
    { name: 'Elixir', category: TechnologyCategory.BACKEND },
    { name: 'GraphQL', category: TechnologyCategory.BACKEND },
    { name: 'REST API', category: TechnologyCategory.BACKEND },
    { name: 'gRPC', category: TechnologyCategory.BACKEND },

    // DATABASE
    { name: 'PostgreSQL', category: TechnologyCategory.DATABASE },
    { name: 'MySQL', category: TechnologyCategory.DATABASE },
    { name: 'MariaDB', category: TechnologyCategory.DATABASE },
    { name: 'MongoDB', category: TechnologyCategory.DATABASE },
    { name: 'Redis', category: TechnologyCategory.DATABASE },
    { name: 'SQLite', category: TechnologyCategory.DATABASE },
    { name: 'Microsoft SQL Server', category: TechnologyCategory.DATABASE },
    { name: 'Oracle Database', category: TechnologyCategory.DATABASE },
    { name: 'Elasticsearch', category: TechnologyCategory.DATABASE },
    { name: 'Cassandra', category: TechnologyCategory.DATABASE },
    { name: 'DynamoDB', category: TechnologyCategory.DATABASE },
    { name: 'Neo4j', category: TechnologyCategory.DATABASE },
    { name: 'Prisma ORM', category: TechnologyCategory.DATABASE },
    { name: 'TypeORM', category: TechnologyCategory.DATABASE },
    { name: 'Drizzle ORM', category: TechnologyCategory.DATABASE },
    { name: 'Supabase', category: TechnologyCategory.DATABASE },
    { name: 'Firebase Firestore', category: TechnologyCategory.DATABASE },

    // DEVOPS
    { name: 'Docker', category: TechnologyCategory.DEVOPS },
    { name: 'Kubernetes', category: TechnologyCategory.DEVOPS },
    { name: 'Terraform', category: TechnologyCategory.DEVOPS },
    { name: 'Ansible', category: TechnologyCategory.DEVOPS },
    { name: 'GitHub Actions', category: TechnologyCategory.DEVOPS },
    { name: 'GitLab CI/CD', category: TechnologyCategory.DEVOPS },
    { name: 'Jenkins', category: TechnologyCategory.DEVOPS },
    { name: 'Helm', category: TechnologyCategory.DEVOPS },
    { name: 'ArgoCD', category: TechnologyCategory.DEVOPS },
    { name: 'Prometheus', category: TechnologyCategory.DEVOPS },
    { name: 'Grafana', category: TechnologyCategory.DEVOPS },
    { name: 'Nginx', category: TechnologyCategory.DEVOPS },
    { name: 'Linux', category: TechnologyCategory.DEVOPS },
    { name: 'Bash / Shell Scripting', category: TechnologyCategory.DEVOPS },

    // CLOUD
    { name: 'Amazon Web Services (AWS)', category: TechnologyCategory.CLOUD },
    { name: 'Microsoft Azure', category: TechnologyCategory.CLOUD },
    { name: 'Google Cloud Platform (GCP)', category: TechnologyCategory.CLOUD },
    { name: 'Cloudflare', category: TechnologyCategory.CLOUD },
    { name: 'Vercel', category: TechnologyCategory.CLOUD },
    { name: 'Netlify', category: TechnologyCategory.CLOUD },
    { name: 'DigitalOcean', category: TechnologyCategory.CLOUD },
    { name: 'Heroku', category: TechnologyCategory.CLOUD },

    // MOBILE
    { name: 'React Native', category: TechnologyCategory.MOBILE },
    { name: 'Flutter', category: TechnologyCategory.MOBILE },
    { name: 'Swift', category: TechnologyCategory.MOBILE },
    { name: 'SwiftUI', category: TechnologyCategory.MOBILE },
    { name: 'Android SDK', category: TechnologyCategory.MOBILE },
    { name: 'Jetpack Compose', category: TechnologyCategory.MOBILE },
    { name: 'Ionic', category: TechnologyCategory.MOBILE },
    { name: 'Expo', category: TechnologyCategory.MOBILE },

    // TESTING
    { name: 'Jest', category: TechnologyCategory.TESTING },
    { name: 'Vitest', category: TechnologyCategory.TESTING },
    { name: 'Cypress', category: TechnologyCategory.TESTING },
    { name: 'Playwright', category: TechnologyCategory.TESTING },
    { name: 'Selenium', category: TechnologyCategory.TESTING },
    { name: 'React Testing Library', category: TechnologyCategory.TESTING },
    { name: 'JUnit', category: TechnologyCategory.TESTING },
    { name: 'PyTest', category: TechnologyCategory.TESTING },
    { name: 'Mocha', category: TechnologyCategory.TESTING },
    { name: 'Postman', category: TechnologyCategory.TESTING },

    // DATA
    { name: 'Apache Kafka', category: TechnologyCategory.DATA },
    { name: 'Apache Spark', category: TechnologyCategory.DATA },
    { name: 'Apache Airflow', category: TechnologyCategory.DATA },
    { name: 'Hadoop', category: TechnologyCategory.DATA },
    { name: 'Snowflake', category: TechnologyCategory.DATA },
    { name: 'Databricks', category: TechnologyCategory.DATA },
    { name: 'Pandas', category: TechnologyCategory.DATA },
    { name: 'NumPy', category: TechnologyCategory.DATA },
    { name: 'Power BI', category: TechnologyCategory.DATA },
    { name: 'Tableau', category: TechnologyCategory.DATA },

    // AI
    { name: 'PyTorch', category: TechnologyCategory.AI },
    { name: 'TensorFlow', category: TechnologyCategory.AI },
    { name: 'OpenAI API', category: TechnologyCategory.AI },
    { name: 'LangChain', category: TechnologyCategory.AI },
    { name: 'Hugging Face', category: TechnologyCategory.AI },
    { name: 'Scikit-learn', category: TechnologyCategory.AI },
    { name: 'Keras', category: TechnologyCategory.AI },
    { name: 'LlamaIndex', category: TechnologyCategory.AI },
    { name: 'Ollama', category: TechnologyCategory.AI },

    // SECURITY
    { name: 'OWASP', category: TechnologyCategory.SECURITY },
    { name: 'OAuth 2.0 / OIDC', category: TechnologyCategory.SECURITY },
    { name: 'JWT (JSON Web Tokens)', category: TechnologyCategory.SECURITY },
    { name: 'Vault (HashiCorp)', category: TechnologyCategory.SECURITY },
    { name: 'SonarQube', category: TechnologyCategory.SECURITY },
    { name: 'Wireshark', category: TechnologyCategory.SECURITY },
    { name: 'Metasploit', category: TechnologyCategory.SECURITY },
    { name: 'Burp Suite', category: TechnologyCategory.SECURITY },

    // DESIGN
    { name: 'Figma', category: TechnologyCategory.DESIGN },
    { name: 'Adobe XD', category: TechnologyCategory.DESIGN },
    { name: 'Sketch', category: TechnologyCategory.DESIGN },
    { name: 'Canva', category: TechnologyCategory.DESIGN },
    { name: 'Photoshop', category: TechnologyCategory.DESIGN },
    { name: 'Photoshop', category: TechnologyCategory.DESIGN },
    { name: 'CorelDRAW', category: TechnologyCategory.DESIGN },
    { name: 'UI/UX Design', category: TechnologyCategory.DESIGN },

    // TOOLS
    { name: 'Git', category: TechnologyCategory.TOOLS },
    { name: 'GitHub', category: TechnologyCategory.TOOLS },
    { name: 'GitLab', category: TechnologyCategory.TOOLS },
    { name: 'Bitbucket', category: TechnologyCategory.TOOLS },
    { name: 'Jira', category: TechnologyCategory.TOOLS },
    { name: 'Confluence', category: TechnologyCategory.TOOLS },
    { name: 'Notion', category: TechnologyCategory.TOOLS },
    { name: 'Trello', category: TechnologyCategory.TOOLS },
    { name: 'VS Code', category: TechnologyCategory.TOOLS },
    { name: 'IntelliJ IDEA', category: TechnologyCategory.TOOLS },
    { name: 'Slack', category: TechnologyCategory.TOOLS },

    // OTHER
    { name: 'Agile / Scrum', category: TechnologyCategory.OTHER },
    { name: 'Kanban', category: TechnologyCategory.OTHER },
    { name: 'WebSockets', category: TechnologyCategory.OTHER },
    { name: 'WebAssembly (Wasm)', category: TechnologyCategory.OTHER },
    { name: 'Clean Architecture', category: TechnologyCategory.OTHER },
    { name: 'Domain-Driven Design (DDD)', category: TechnologyCategory.OTHER },
    { name: 'Microservices', category: TechnologyCategory.OTHER },

    // EMBEDDED_SYSTEMS
    { name: 'C', category: TechnologyCategory.EMBEDDED_SYSTEMS },
    { name: 'C++', category: TechnologyCategory.EMBEDDED_SYSTEMS },
    { name: 'Embedded Rust', category: TechnologyCategory.EMBEDDED_SYSTEMS },
    { name: 'FreeRTOS', category: TechnologyCategory.EMBEDDED_SYSTEMS },
    { name: 'STM32', category: TechnologyCategory.EMBEDDED_SYSTEMS },
    { name: 'ESP32 / ESP8266', category: TechnologyCategory.EMBEDDED_SYSTEMS },
    { name: 'Arduino', category: TechnologyCategory.EMBEDDED_SYSTEMS },
    { name: 'Raspberry Pi', category: TechnologyCategory.EMBEDDED_SYSTEMS },
    { name: 'ARM Cortex', category: TechnologyCategory.EMBEDDED_SYSTEMS },
    { name: 'Embedded Linux', category: TechnologyCategory.EMBEDDED_SYSTEMS },
    { name: 'Yocto Project', category: TechnologyCategory.EMBEDDED_SYSTEMS },
    { name: 'Zephyr RTOS', category: TechnologyCategory.EMBEDDED_SYSTEMS },
    { name: 'UART / SPI / I2C / CAN', category: TechnologyCategory.EMBEDDED_SYSTEMS },
    { name: 'BLE (Bluetooth Low Energy)', category: TechnologyCategory.EMBEDDED_SYSTEMS },
    { name: 'Zigbee / LoRaWAN', category: TechnologyCategory.EMBEDDED_SYSTEMS },
    { name: 'Microchip PIC', category: TechnologyCategory.EMBEDDED_SYSTEMS },
    { name: 'AVR', category: TechnologyCategory.EMBEDDED_SYSTEMS },
    { name: 'MATLAB / Simulink', category: TechnologyCategory.EMBEDDED_SYSTEMS },
    { name: 'VHDL / Verilog', category: TechnologyCategory.EMBEDDED_SYSTEMS },
    { name: 'FPGA', category: TechnologyCategory.EMBEDDED_SYSTEMS },

    // MANAGEMENT
    { name: 'Agile Software Development', category: TechnologyCategory.MANAGEMENT },
    { name: 'Scrum', category: TechnologyCategory.MANAGEMENT },
    { name: 'Kanban', category: TechnologyCategory.MANAGEMENT },
    { name: 'OKRs (Objectives and Key Results)', category: TechnologyCategory.MANAGEMENT },
    { name: 'KPIs & Metrics Management', category: TechnologyCategory.MANAGEMENT },
    { name: 'Prince2', category: TechnologyCategory.MANAGEMENT },
    { name: 'PMP (Project Management Professional)', category: TechnologyCategory.MANAGEMENT },
    { name: 'SAFe (Scaled Agile Framework)', category: TechnologyCategory.MANAGEMENT },
    { name: 'Jira Software', category: TechnologyCategory.MANAGEMENT },
    { name: 'Confluence', category: TechnologyCategory.MANAGEMENT },
    { name: 'Asana', category: TechnologyCategory.MANAGEMENT },
    { name: 'ClickUp', category: TechnologyCategory.MANAGEMENT },
    { name: 'Monday.com', category: TechnologyCategory.MANAGEMENT },
    { name: 'Trello', category: TechnologyCategory.MANAGEMENT },
    { name: 'Basecamp', category: TechnologyCategory.MANAGEMENT },
    { name: 'Product Roadmap Planning', category: TechnologyCategory.MANAGEMENT },
    { name: 'Stakeholder Management', category: TechnologyCategory.MANAGEMENT },
    { name: 'Risk Management', category: TechnologyCategory.MANAGEMENT },
    { name: 'Resource Allocation', category: TechnologyCategory.MANAGEMENT },
    { name: 'Sprint Planning & Grooming', category: TechnologyCategory.MANAGEMENT },
  ];

  for (const tech of technologiesData) {
    await prisma.technology.upsert({
      where: { name: tech.name },
      update: { category: tech.category },
      create: tech,
    });
  }

  console.log(`Successfully seeded ${technologiesData.length} technologies!`);
}